#!/usr/bin/env python
import os

def application(environ, start_request):
    if not 'trac.env_parent_dir' in environ:
        environ.setdefault('trac.env_path', os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'trac', 'env'))
    from trac.web.main import dispatch_request
    return dispatch_request(environ, start_request)


#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.handle_request()
